In [6]:
import numpy as np 
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
df = pd.read_csv("https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv")
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
X_scaled = StandardScaler().fit_transform(df.values[:,:4])
X_scaled[:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [8]:
features = X_scaled.T
cov_matrix = np.cov(features)
cov_matrix[:5]

array([[ 1.00671141, -0.11010327,  0.87760486,  0.82344326],
       [-0.11010327,  1.00671141, -0.42333835, -0.358937  ],
       [ 0.87760486, -0.42333835,  1.00671141,  0.96921855],
       [ 0.82344326, -0.358937  ,  0.96921855,  1.00671141]])

In [9]:
values, vectors = np.linalg.eig(cov_matrix)


In [10]:
P = vectors.T.dot(features)
print(P.T)

[[-2.26454173e+00 -5.05703903e-01 -1.21943348e-01  2.30733235e-02]
 [-2.08642550e+00  6.55404729e-01 -2.27250832e-01  1.03208244e-01]
 [-2.36795045e+00  3.18477311e-01  5.14796236e-02  2.78252250e-02]
 [-2.30419716e+00  5.75367713e-01  9.88604444e-02 -6.63114622e-02]
 [-2.38877749e+00 -6.74767397e-01  2.14278490e-02 -3.73972870e-02]
 [-2.07053681e+00 -1.51854856e+00  3.06842583e-02  4.39877494e-03]
 [-2.44571134e+00 -7.45626750e-02  3.42197636e-01 -3.80965668e-02]
 [-2.23384186e+00 -2.47613932e-01 -8.25744645e-02 -2.55051623e-02]
 [-2.34195768e+00  1.09514636e+00  1.53562399e-01 -2.67938291e-02]
 [-2.18867576e+00  4.48629048e-01 -2.46559522e-01 -3.99073035e-02]
 [-2.16348656e+00 -1.07059558e+00 -2.64009373e-01  1.53011377e-02]
 [-2.32737775e+00 -1.58587455e-01  1.00165616e-01 -1.34554258e-01]
 [-2.22408272e+00  7.09118158e-01 -2.23214514e-01  2.63061382e-03]
 [-2.63971626e+00  9.38281982e-01  1.89570030e-01 -1.94220183e-02]
 [-2.19229151e+00 -1.88997851e+00 -4.69480095e-01  1.92782042e

In [13]:
pca = PCA(n_components=4)
pca.fit_transform(X_scaled)

array([[-2.26454173e+00,  5.05703903e-01, -1.21943348e-01,
        -2.30733235e-02],
       [-2.08642550e+00, -6.55404729e-01, -2.27250832e-01,
        -1.03208244e-01],
       [-2.36795045e+00, -3.18477311e-01,  5.14796236e-02,
        -2.78252250e-02],
       [-2.30419716e+00, -5.75367713e-01,  9.88604444e-02,
         6.63114622e-02],
       [-2.38877749e+00,  6.74767397e-01,  2.14278490e-02,
         3.73972870e-02],
       [-2.07053681e+00,  1.51854856e+00,  3.06842583e-02,
        -4.39877494e-03],
       [-2.44571134e+00,  7.45626750e-02,  3.42197636e-01,
         3.80965668e-02],
       [-2.23384186e+00,  2.47613932e-01, -8.25744645e-02,
         2.55051623e-02],
       [-2.34195768e+00, -1.09514636e+00,  1.53562399e-01,
         2.67938291e-02],
       [-2.18867576e+00, -4.48629048e-01, -2.46559522e-01,
         3.99073035e-02],
       [-2.16348656e+00,  1.07059558e+00, -2.64009373e-01,
        -1.53011377e-02],
       [-2.32737775e+00,  1.58587455e-01,  1.00165616e-01,
      