In [1]:
import numpy as np 
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler


In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/Sonar.csv")
df.head()


V1      V2      V3      V4      V5      V6      V7      V8      V9  \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

      V10  ...     V52     V53     V54     V55     V56     V57     V58  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

      V59     V60  Class  
0  0.0090  0.0032      1  
1  0.0052  0.0044      1  
2  0.0095  0.0078      1  
3  0.0040  0.0117      1  
4  0.0107  0.0094      1  

[5 rows x 61 columns]

In [3]:
X_scaled=df.values[:,:-1]
X_scaled

array([[0.02  , 0.0371, 0.0428, ..., 0.0084, 0.009 , 0.0032],
       [0.0453, 0.0523, 0.0843, ..., 0.0049, 0.0052, 0.0044],
       [0.0262, 0.0582, 0.1099, ..., 0.0164, 0.0095, 0.0078],
       ...,
       [0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
       [0.0303, 0.0353, 0.049 , ..., 0.0079, 0.0036, 0.0048],
       [0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115]])

In [4]:
features = X_scaled.T
cov_matrix = np.cov(features)
cov_matrix

array([[5.28582124e-04, 5.57646155e-04, 5.04951119e-04, ...,
        5.47587333e-05, 5.07518362e-05, 4.01458652e-05],
       [5.57646155e-04, 1.08635692e-03, 9.87831957e-04, ...,
        7.52845764e-05, 7.17564530e-05, 5.94907980e-05],
       [5.04951119e-04, 9.87831957e-04, 1.47671978e-03, ...,
        8.30673017e-05, 1.00965183e-04, 7.22967231e-05],
       ...,
       [5.47587333e-05, 7.52845764e-05, 8.30673017e-05, ...,
        4.18588397e-05, 2.20053056e-05, 1.07358765e-05],
       [5.07518362e-05, 7.17564530e-05, 1.00965183e-04, ...,
        2.20053056e-05, 3.82094900e-05, 1.99925506e-05],
       [4.01458652e-05, 5.94907980e-05, 7.22967231e-05, ...,
        1.07358765e-05, 1.99925506e-05, 2.53113970e-05]])

In [5]:
values, vectors = np.linalg.eig(cov_matrix)

In [13]:
tot = sum(values)
var_exp = [(i / tot)*100 for i in sorted(values, reverse=True)]
var_exp

[31.971149479250844,
 20.38305953728048,
 8.555819679369264,
 6.45932204596332,
 5.164155930867674,
 4.4514018246418345,
 4.2076958182616035,
 2.632652024792219,
 2.2300365707046788,
 1.9218172736583883,
 1.5653089042301445,
 1.3592722208650767,
 1.1701421917182402,
 0.9568011142404605,
 0.8733245571209355,
 0.7664945212773384,
 0.7194404870969742,
 0.5655949002765748,
 0.5273139393496973,
 0.4881195274986719,
 0.36590400819513086,
 0.2933970304461112,
 0.26791630102628117,
 0.23999330015828094,
 0.23204123503503546,
 0.21589497354309026,
 0.15637260367892894,
 0.14049699042011726,
 0.1297738318785073,
 0.11840549646584479,
 0.09671993297446485,
 0.09092942195605552,
 0.07612202305422579,
 0.07236982276696283,
 0.0700007357537302,
 0.06514964602837871,
 0.05478668472987769,
 0.05252344694365402,
 0.048753063747574606,
 0.04042165240042081,
 0.0394505882703405,
 0.0362972155625524,
 0.02749953746301098,
 0.023346011641621676,
 0.019255521994584742,
 0.01485979871021927,
 0.0091640316529

In [15]:
np.cumsum(var_exp)

array([ 31.97114948,  52.35420902,  60.9100287 ,  67.36935074,
        72.53350667,  76.9849085 ,  81.19260432,  83.82525634,
        86.05529291,  87.97711018,  89.54241909,  90.90169131,
        92.0718335 ,  93.02863462,  93.90195917,  94.66845369,
        95.38789418,  95.95348908,  96.48080302,  96.96892255,
        97.33482656,  97.62822359,  97.89613989,  98.13613319,
        98.36817442,  98.5840694 ,  98.740442  ,  98.88093899,
        99.01071282,  99.12911832,  99.22583825,  99.31676767,
        99.3928897 ,  99.46525952,  99.53526026,  99.6004099 ,
        99.65519659,  99.70772003,  99.7564731 ,  99.79689475,
        99.83634534,  99.87264255,  99.90014209,  99.9234881 ,
        99.94274362,  99.95760342,  99.96676745,  99.97463659,
        99.98174152,  99.98634739,  99.98952777,  99.99201079,
        99.9938669 ,  99.99537982,  99.99660719,  99.99767241,
        99.99845705,  99.99913228,  99.99966774, 100.        ])

In [16]:
P = vectors.T.dot(features)
print(P.T)

[[-2.89418819e-01 -4.10520740e-02  2.20670062e+00 ... -3.31544755e-03
  -5.26852232e-03  9.05558569e-04]
 [ 1.25734106e+00 -7.39698389e-01  9.85253893e-01 ...  5.72278410e-03
  -5.91226903e-03  6.51200955e-03]
 [ 6.12560494e-01 -5.95867712e-01  1.57339454e+00 ... -5.69901710e-03
  -1.53530343e-03  4.55109689e-03]
 ...
 [-1.10594056e-02  1.43020074e+00  1.56931418e+00 ... -1.51192774e-04
   4.66976424e-03 -2.30499788e-04]
 [ 3.32434490e-01  1.27431041e+00  1.61973268e+00 ... -2.74639587e-03
   8.23790169e-04 -2.59318857e-03]
 [ 3.37788263e-01  1.19086713e+00  1.81050010e+00 ... -3.29089817e-03
  -4.65006168e-03  4.59836901e-03]]


In [18]:
pd.DataFrame(P.T,columns=var_exp)

31.971149  20.383060  8.555820   6.459322   5.164156   4.451402   \
0    -0.289419  -0.041052   2.206701   1.397359   0.446548   0.293752   
1     1.257341  -0.739698   0.985254   1.882791   0.976399  -0.041176   
2     0.612560  -0.595868   1.573395   2.638399   0.759438   0.438341   
3    -0.565362  -0.412522   1.832800   1.665111   0.136278  -0.260460   
4     0.351429   0.055373   1.180809   1.915800   0.826183   0.084628   
..         ...        ...        ...        ...        ...        ...   
203   0.244892   1.309985   1.553740   1.796884   0.674889   0.040205   
204   0.067525   1.432148   1.615790   1.821204   0.873600   0.124738   
205  -0.011059   1.430201   1.569314   1.717666   0.853895   0.122233   
206   0.332434   1.274310   1.619733   1.708852   0.543102   0.222109   
207   0.337788   1.190867   1.810500   1.730981   0.662413   0.167458   

     4.207696   2.632652   2.230037   1.921817   ...  0.003180   0.002483   \
0    -1.005711  -0.012276  -0.106693  -0.352603  ...   0.016620  -0.008969   
1    -0.838307  -0.323045  -0.127011   0.037980  ...   0.003615  -0.000312   
2    -0.990782  -0.012765  -0.120185   0.404011  ...   0.009771   0.006300   
3    -0.085406   0.283016  -0.668043   0.402246  ...  -0.001690   0.007233   
4    -0.964533  -0.003993  -0.014035   0.384729  ...  -0.002294   0.023999   
..         ...        ...        ...        ...  ...        ...        ...   
203  -0.574191  -0.115371  -0.103133   0.229631  ...   0.019340   0.017880   
204  -0.499468  -0.202275  -0.201790   0.268747  ...   0.012860   0.002410   
205  -0.532183  -0.163348  -0.203170   0.278495  ...   0.009860   0.006705   
206  -0.546937  -0.004888  -0.156811   0.136571  ...   0.018093   0.000819   
207  -0.544868   0.083424  -0.012049   0.109585  ...   0.004014   0.018519   

     0.001856   0.001513   0.001227   0.001065   0.000785   0.000675   \
0     0.004563   0.012264  -0.006702  -0.001604  -0.002095  -0.003315   
1    -0.003130   0.005205   0.000768  -0.004169   0.004295   0.005723   
2    -0.010958   0.008098  -0.011920  -0.002824  -0.002477  -0.005699   
3     0.011144  -0.002131  -0.005583   0.004319   0.002542  -0.001577   
4    -0.001650  -0.001806   0.005903  -0.001616  -0.000237  -0.000217   
..         ...        ...        ...        ...        ...        ...   
203   0.001078   0.004042   0.010040   0.008103  -0.000708  -0.001631   
204  -0.003367  -0.004331   0.004688   0.005729   0.003754  -0.002523   
205  -0.003578   0.008375  -0.009298  -0.000095  -0.002051  -0.000151   
206  -0.000816   0.000036  -0.000634   0.005458   0.001246  -0.002746   
207  -0.003832   0.007918   0.006907   0.000969   0.001672  -0.003291   

     0.000535   0.000332   
0    -0.005269   0.000906  
1    -0.005912   0.006512  
2    -0.001535   0.004551  
3     0.000472  -0.000088  
4    -0.002148   0.000705  
..         ...        ...  
203   0.001991   0.004099  
204  -0.002223  -0.002221  
205   0.004670  -0.000230  
206   0.000824  -0.002593  
207  -0.004650   0.004598  

[208 rows x 60 columns]